modLoader="javafml"
loaderVersion="[40,)"
license="All Right Reserved"
issueTrackerURL=""
displayURL=""
###logoFile="bd_dtn_banner.png"
[[mods]] #mandatory
    modId="skinexpansion_dtn"
    version="${file.jarVersion}"
###    updateJSONURL=""
    displayName="DTN Skin Expansion Addon"
    credits="MashXP (Converting Models, Making the Addon), DashieDev (Providing the Base for the Addon)"
    authors="mashxp"
    description=" MORE SKINS!!!"
[[dependencies.skinexpansion_dtn]] #optional
    modId="forge"
    mandatory=true
    versionRange="[40.0.18,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.skinexpansion_dtn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.skinexpansion_dtn]]
    modId="doggytalents"
    mandatory=true
    versionRange="[1.17.0,)"
    ordering="NONE"
    side="BOTH"