modLoader="javafml"
loaderVersion="${neofml_version_range}"
license="All Right Reserved"
issueTrackerURL=""
displayURL=""
logoFile="dtn_community.png"
[[mods]] #mandatory
    modId="skinexpansion_dtn"
    version="${file.jarVersion}"
###    updateJSONURL=""
    displayName="DTN Community Skin Expansion Addon"
    credits="MashXP (Converting Models, Making the Addon), DashieDev (Providing the Base for the Addon)"
    authors="mashxp"
    description="MORE SKINS!!!"
[[dependencies.skinexpansion_dtn]] #optional
    modId="neoforge"
    type="required"
    versionRange="[20.5,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.skinexpansion_dtn]]
    modId="minecraft"
    type="required"
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.skinexpansion_dtn]]
    modId="doggytalents"
    type="required"
    versionRange="[1.17.0,)"
    ordering="NONE"
    side="BOTH"